### PR TITLE
Sender hazel

### PR DESCRIPTION
**Pull request by hazelweeling**
Added test cases for C-FIND and C-SEND.

### CODE REVIEW

**Comment by jkrol8** [comment]
This looks good - we can work on splitting up the function in cpp next week

**Comment by hazelweeling** [comment]
That’s the plan! Thanks Julia :)

**Comment by jkrol8** [comment]
What you showed me looks good - can you resolve the conflict in CMakeLists

**Comment by hazelweeling** [comment]
> What you showed me looks good - can you resolve the conflict in CMakeLists

Yes, merge conflicts should have resolved.

**Comment by hazelweeling** [comment]
What are all these checks that are unsuccessful? Are they automated?

**Comment by jkrol8** [comment]
Delete the ")" on line 79 in CMakeLists

**Pull request merged**
